#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu
  - sleep 10
  - docker pull ${dockerhub_user}/hr-app:latest
  - docker run -d -p 80:8000 --restart always --name hr-app ${dockerhub_user}/hr-app:latest
